### ISSUE TITLE
when use named pipe, it will appear 'No such file or directory'

### ISSUE THREAD

**Issue by dawnworld** [chef-boneyard/win32-pipe#3]
I use vmware generate a named pipe (\\.\pipe\com_1)
code like this

``` ruby
Pipe::Client.new('\\\\.\\pipe\\com_1') do |pipe|
  data = pipe.read
  puts "get it #{data}"
end
```

received error:
in `initialize': No such file or directory - CreateFile (Errno::ENOENT)

**Comment by djberg96** [comment]
You have a pipe server with a physical drive name? I don't understand what you're trying to do.

**Comment by dawnworld** [comment]
No, I use Vmware. My Host is Win7, my virtual machine is WinXP. Now, I use Vmware to add a virtual serial port(virtual hardware, selected named pipe, like \\.\pipe\com_1 ), I want host to communicat with my virtual machine through the named pipe. My ruby program runs on the host.

``` ruby
PIPE_NAME = "\\\\.\\pipe\\com_1"
 output = open(PIPE_NAME, "w")
 output.puts "hello i'm from ruby"
 output.flush
```

this code can run well, but I use Pipe::Client， it will appear  above-mentioned error

**Comment by djberg96** [comment]
Do me a favor and try changing the 3rd parameter to CreateFile in client.rb to 0 and see if that works.

**Comment by phasis68** [comment]
According to https://github.com/djberg96/win32-pipe/blob/ffi/lib/win32/pipe.rb#L85,
you should use `com_1` instead of `\\\\.\\pipe\\com_1`

Try with

``` ruby
Pipe::Client.new('com_1') do |pipe|
  data = pipe.read
  puts "get it #{data}"
end
```

**Comment by dawnworld** [comment]
thanks @phasis68 and @djberg96  , it goes well!

**Comment by djberg96** [comment]
I should read my own docs, lol. Thanks, glad it got worked out.
