### ISSUE TITLE
Cannot find CreateFile

### ISSUE THREAD

**Issue by smprather** [chef-boneyard/win32-pipe#5]
Hi--

I tried to run the server.rb/client.rb Hello World, but I got this.

In one terminal:
c:>ruby server.rb
Got Hello World from client
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/win32-pipe-0.3.7/lib/win32/pipe/client.rb:52:in `initialize': No such file or directory - CreateFile (Errno::ENOENT)
        from server.rb:27:in`new'
        from server.rb:27:in `<main>'

In another:
c:>ruby client.rb

I have both win32-api and win32-pipe installed on a fresh install of Ruby2.2.

Thanks!
--Myles

**Comment by smprather** [comment]
Sorry, user error. But still, there's a reference to CreateFile in the code. Can that code ever work? Thanks. I'm trying to write a Ruby script to send commands to mpg123 -R --fifo mpg123.control, but it's not going very well. Thanks again.

**Comment by djberg96** [comment]
@smprather The CreateFile function works on I/O devices as well as files, so yes, it should work. If you have any other issues, please let me know.
